### ISSUE TITLE
Android and ios devices can't chat each other

### ISSUE THREAD

**Issue by topninja** [bridgefy/react-native-bridgefy#9]
Thanks bridgefy team for make this awesome sdk!
...
I built chat app by using this react native bridgefy sdk.
chat app is working well between ios devices and also between android devices.
but not working between android and ios devices each other.
looks like they detected device but chat is not working.
I can't find what the issue is.
I tested also by your bridgfy ios app and android app that are published on playstore and appstore and looks like they're also not working.
Please help this, or this is impossible?
Thanks

**Comment by jorgeribs** [comment]
Hi there! Thanks for checking out the Bridgefy SDK. As we state [on this website](https://bridgefy.me/sdk-legacy/), this is a version that is a bit buggy, and we're working on a new and improved Bridgefy SDK! We're publishing it very very soon, and look forward to getting your feedback!

**Comment by topninja** [comment]
Great. looking forward it.

**Comment by hosseinfooo** [comment]
hi 
Thanks bridgefy team for this sdk!

can you say when you publish it?(i mean version Without bug(

**Comment by jorgeribs** [comment]
It will come out in the next 2-3 months!

Gracias,

*– Jorge Rios*

**Comment by hoseinfo** [comment]
hello
can't we use sdk version 2 now for test?

**Comment by topninja** [comment]
What's going on?
5 months passed..
